rndnumbersPerSeed: 100000
seeds: 
  - 13213

arrivals: 
  fila1: 2.0

queues: 
  fila1: 
    servers: 1
    capacity: -1
    minArrival: 2.0
    maxArrival: 4.0
    minService: 1.0
    maxService: 2.0
  fila2: 
    servers: 2
    capacity: 5
    minService: 4.0
    maxService: 8.0
  fila3: 
    servers: 2
    capacity: 10
    minService: 5.0
    maxService: 15.0

network: 
  - source: fila1
    target: fila2
    probability: 0.8
  - source: fila1
    target: fila3
    probability: 0.2
  - source: fila2
    target: fila2
    probability: 0.5
  - source: fila2
    target: null
    probability: 0.2
  - source: fila2
    target: fila1
    probability: 0.3
  - source: fila3
    target: fila3
    probability: 0.7
  - source: fila3
    target: null
    probability: 0.3